enum Collection {
  DISASTER = 'Disaster',
  CARS = 'Cars',
  INVASION = 'Invasion',
  SPACE = 'Space',
  ROBOTS = 'Robots',
  CRIMINALS = 'Criminals',
  MCU = 'MCU',
  DEU = 'DEU',
  FANTASY_WORLDS = 'FantasyWorlds',
  TOP_10 = 'Top10',
  FUTURE = 'Future',
  LEGENDS = 'Legends',
  SUPERHEROES = 'Superheroes',
  AGENTS_DETECTIVES = 'AgentsDetectives',
  HISTORICAL_EVENTS = 'HistoricalEvents',
  DYSTOPIA = 'Dystopia',
  MARTIAL_ARTS = 'MartialArts',
  HPU = 'HPU',
  ROM_COM = 'RomCom',
  CINEMATOGRAPH = 'Cinematograph',
  MYSTERIES = 'Mysteries',
  MONSTERS = 'Monsters',
  CHRISTMAS = 'Christmas',
  SWU = 'SWU',
  ANIMALS = 'Animals',
  MEU = 'MEU',
  BASED_ON_TRUE = 'BasedOnTrue',
  SPORT = 'Sport',
  SKILLS = 'Skills',
  ANIME = 'Anime',
}

export { Collection };
