/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StatisticImport } from './routes/statistic'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as ConsoleImport } from './routes/_console'
import { Route as IndexImport } from './routes/index'
import { Route as FilmIdImport } from './routes/film.$id'
import { Route as ConsoleConsolePendingImport } from './routes/_console/console.pending'
import { Route as ConsoleConsoleManageImport } from './routes/_console/console.manage'
import { Route as ConsoleConsoleAdditionalImport } from './routes/_console/console.additional'
import { Route as ConsoleConsoleManageIdImport } from './routes/_console/console.manage_.$id'

// Create/Update Routes

const StatisticRoute = StatisticImport.update({
  id: '/statistic',
  path: '/statistic',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const ConsoleRoute = ConsoleImport.update({
  id: '/_console',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FilmIdRoute = FilmIdImport.update({
  id: '/film/$id',
  path: '/film/$id',
  getParentRoute: () => rootRoute,
} as any)

const ConsoleConsolePendingRoute = ConsoleConsolePendingImport.update({
  id: '/console/pending',
  path: '/console/pending',
  getParentRoute: () => ConsoleRoute,
} as any)

const ConsoleConsoleManageRoute = ConsoleConsoleManageImport.update({
  id: '/console/manage',
  path: '/console/manage',
  getParentRoute: () => ConsoleRoute,
} as any)

const ConsoleConsoleAdditionalRoute = ConsoleConsoleAdditionalImport.update({
  id: '/console/additional',
  path: '/console/additional',
  getParentRoute: () => ConsoleRoute,
} as any)

const ConsoleConsoleManageIdRoute = ConsoleConsoleManageIdImport.update({
  id: '/console/manage_/$id',
  path: '/console/manage/$id',
  getParentRoute: () => ConsoleRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_console': {
      id: '/_console'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ConsoleImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/statistic': {
      id: '/statistic'
      path: '/statistic'
      fullPath: '/statistic'
      preLoaderRoute: typeof StatisticImport
      parentRoute: typeof rootRoute
    }
    '/film/$id': {
      id: '/film/$id'
      path: '/film/$id'
      fullPath: '/film/$id'
      preLoaderRoute: typeof FilmIdImport
      parentRoute: typeof rootRoute
    }
    '/_console/console/additional': {
      id: '/_console/console/additional'
      path: '/console/additional'
      fullPath: '/console/additional'
      preLoaderRoute: typeof ConsoleConsoleAdditionalImport
      parentRoute: typeof ConsoleImport
    }
    '/_console/console/manage': {
      id: '/_console/console/manage'
      path: '/console/manage'
      fullPath: '/console/manage'
      preLoaderRoute: typeof ConsoleConsoleManageImport
      parentRoute: typeof ConsoleImport
    }
    '/_console/console/pending': {
      id: '/_console/console/pending'
      path: '/console/pending'
      fullPath: '/console/pending'
      preLoaderRoute: typeof ConsoleConsolePendingImport
      parentRoute: typeof ConsoleImport
    }
    '/_console/console/manage_/$id': {
      id: '/_console/console/manage_/$id'
      path: '/console/manage/$id'
      fullPath: '/console/manage/$id'
      preLoaderRoute: typeof ConsoleConsoleManageIdImport
      parentRoute: typeof ConsoleImport
    }
  }
}

// Create and export the route tree

interface ConsoleRouteChildren {
  ConsoleConsoleAdditionalRoute: typeof ConsoleConsoleAdditionalRoute
  ConsoleConsoleManageRoute: typeof ConsoleConsoleManageRoute
  ConsoleConsolePendingRoute: typeof ConsoleConsolePendingRoute
  ConsoleConsoleManageIdRoute: typeof ConsoleConsoleManageIdRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleConsoleAdditionalRoute: ConsoleConsoleAdditionalRoute,
  ConsoleConsoleManageRoute: ConsoleConsoleManageRoute,
  ConsoleConsolePendingRoute: ConsoleConsolePendingRoute,
  ConsoleConsoleManageIdRoute: ConsoleConsoleManageIdRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ConsoleRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/statistic': typeof StatisticRoute
  '/film/$id': typeof FilmIdRoute
  '/console/additional': typeof ConsoleConsoleAdditionalRoute
  '/console/manage': typeof ConsoleConsoleManageRoute
  '/console/pending': typeof ConsoleConsolePendingRoute
  '/console/manage/$id': typeof ConsoleConsoleManageIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ConsoleRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/statistic': typeof StatisticRoute
  '/film/$id': typeof FilmIdRoute
  '/console/additional': typeof ConsoleConsoleAdditionalRoute
  '/console/manage': typeof ConsoleConsoleManageRoute
  '/console/pending': typeof ConsoleConsolePendingRoute
  '/console/manage/$id': typeof ConsoleConsoleManageIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_console': typeof ConsoleRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/statistic': typeof StatisticRoute
  '/film/$id': typeof FilmIdRoute
  '/_console/console/additional': typeof ConsoleConsoleAdditionalRoute
  '/_console/console/manage': typeof ConsoleConsoleManageRoute
  '/_console/console/pending': typeof ConsoleConsolePendingRoute
  '/_console/console/manage_/$id': typeof ConsoleConsoleManageIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/statistic'
    | '/film/$id'
    | '/console/additional'
    | '/console/manage'
    | '/console/pending'
    | '/console/manage/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/statistic'
    | '/film/$id'
    | '/console/additional'
    | '/console/manage'
    | '/console/pending'
    | '/console/manage/$id'
  id:
    | '__root__'
    | '/'
    | '/_console'
    | '/about'
    | '/login'
    | '/statistic'
    | '/film/$id'
    | '/_console/console/additional'
    | '/_console/console/manage'
    | '/_console/console/pending'
    | '/_console/console/manage_/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  StatisticRoute: typeof StatisticRoute
  FilmIdRoute: typeof FilmIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  StatisticRoute: StatisticRoute,
  FilmIdRoute: FilmIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_console",
        "/about",
        "/login",
        "/statistic",
        "/film/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_console": {
      "filePath": "_console.tsx",
      "children": [
        "/_console/console/additional",
        "/_console/console/manage",
        "/_console/console/pending",
        "/_console/console/manage_/$id"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/statistic": {
      "filePath": "statistic.tsx"
    },
    "/film/$id": {
      "filePath": "film.$id.tsx"
    },
    "/_console/console/additional": {
      "filePath": "_console/console.additional.tsx",
      "parent": "/_console"
    },
    "/_console/console/manage": {
      "filePath": "_console/console.manage.tsx",
      "parent": "/_console"
    },
    "/_console/console/pending": {
      "filePath": "_console/console.pending.tsx",
      "parent": "/_console"
    },
    "/_console/console/manage_/$id": {
      "filePath": "_console/console.manage_.$id.tsx",
      "parent": "/_console"
    }
  }
}
ROUTE_MANIFEST_END */
