services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - apps/api/.env.docker
    depends_on:
      database:
        condition: service_healthy
        restart: true

  database:
    image: postgres:17-bookworm
    restart: unless-stopped
    ports:
      - "54321:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  s3_local:
    image: localstack/localstack:latest
    platform: linux/arm64
    ports:
      - "45661:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack/data
      - AWS_DEFAULT_REGION=eu-central-1
    volumes:
      - ./localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata: