/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticRouteRouteImport } from './routes/statistic/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as FilmsIdRouteRouteImport } from './routes/films/$id/route'
import { Route as ConsolePendingFilmsRouteRouteImport } from './routes/console/pending-films/route'
import { Route as ConsolePageContentRouteRouteImport } from './routes/console/page-content/route'
import { Route as ConsoleGeneralRouteRouteImport } from './routes/console/general/route'
import { Route as ConsoleFilmsRouteRouteImport } from './routes/console/films/route'
import { Route as ConsoleCollectionEventsRouteRouteImport } from './routes/console/collection-events/route'
import { Route as FilmsIdIndexRouteImport } from './routes/films/$id/index'
import { Route as FilmsIdRelatedRouteImport } from './routes/films/$id/related'
import { Route as ConsolePageContentIdRouteImport } from './routes/console/page-content_/$id'
import { Route as ConsoleFilmsIdRouteImport } from './routes/console/films_/$id'
import { Route as ConsoleGeneralStudiosRouteRouteImport } from './routes/console/general_/studios/route'
import { Route as ConsoleGeneralPeopleRouteRouteImport } from './routes/console/general_/people/route'
import { Route as ConsoleGeneralGenresRouteRouteImport } from './routes/console/general_/genres/route'
import { Route as ConsoleGeneralCountriesRouteRouteImport } from './routes/console/general_/countries/route'
import { Route as ConsoleGeneralCollectionsRouteRouteImport } from './routes/console/general_/collections/route'
import { Route as ConsoleGeneralAwardsRouteRouteImport } from './routes/console/general_/awards/route'
import { Route as ConsoleGeneralAwardsIdRouteImport } from './routes/console/general_/awards_/$id'

const StatisticRouteRoute = StatisticRouteRouteImport.update({
  id: '/statistic',
  path: '/statistic',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIdRouteRoute = FilmsIdRouteRouteImport.update({
  id: '/films/$id',
  path: '/films/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolePendingFilmsRouteRoute =
  ConsolePendingFilmsRouteRouteImport.update({
    id: '/pending-films',
    path: '/pending-films',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsolePageContentRouteRoute = ConsolePageContentRouteRouteImport.update({
  id: '/page-content',
  path: '/page-content',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleGeneralRouteRoute = ConsoleGeneralRouteRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFilmsRouteRoute = ConsoleFilmsRouteRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCollectionEventsRouteRoute =
  ConsoleCollectionEventsRouteRouteImport.update({
    id: '/collection-events',
    path: '/collection-events',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const FilmsIdIndexRoute = FilmsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmsIdRouteRoute,
} as any)
const FilmsIdRelatedRoute = FilmsIdRelatedRouteImport.update({
  id: '/related',
  path: '/related',
  getParentRoute: () => FilmsIdRouteRoute,
} as any)
const ConsolePageContentIdRoute = ConsolePageContentIdRouteImport.update({
  id: '/page-content_/$id',
  path: '/page-content/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFilmsIdRoute = ConsoleFilmsIdRouteImport.update({
  id: '/films_/$id',
  path: '/films/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleGeneralStudiosRouteRoute =
  ConsoleGeneralStudiosRouteRouteImport.update({
    id: '/general_/studios',
    path: '/general/studios',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleGeneralPeopleRouteRoute =
  ConsoleGeneralPeopleRouteRouteImport.update({
    id: '/general_/people',
    path: '/general/people',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleGeneralGenresRouteRoute =
  ConsoleGeneralGenresRouteRouteImport.update({
    id: '/general_/genres',
    path: '/general/genres',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleGeneralCountriesRouteRoute =
  ConsoleGeneralCountriesRouteRouteImport.update({
    id: '/general_/countries',
    path: '/general/countries',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleGeneralCollectionsRouteRoute =
  ConsoleGeneralCollectionsRouteRouteImport.update({
    id: '/general_/collections',
    path: '/general/collections',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleGeneralAwardsRouteRoute =
  ConsoleGeneralAwardsRouteRouteImport.update({
    id: '/general_/awards',
    path: '/general/awards',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleGeneralAwardsIdRoute = ConsoleGeneralAwardsIdRouteImport.update({
  id: '/general_/awards_/$id',
  path: '/general/awards/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/statistic': typeof StatisticRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/general': typeof ConsoleGeneralRouteRoute
  '/console/page-content': typeof ConsolePageContentRouteRoute
  '/console/pending-films': typeof ConsolePendingFilmsRouteRoute
  '/films/$id': typeof FilmsIdRouteRouteWithChildren
  '/': typeof HomeIndexRoute
  '/console/general/awards': typeof ConsoleGeneralAwardsRouteRoute
  '/console/general/collections': typeof ConsoleGeneralCollectionsRouteRoute
  '/console/general/countries': typeof ConsoleGeneralCountriesRouteRoute
  '/console/general/genres': typeof ConsoleGeneralGenresRouteRoute
  '/console/general/people': typeof ConsoleGeneralPeopleRouteRoute
  '/console/general/studios': typeof ConsoleGeneralStudiosRouteRoute
  '/console/films/$id': typeof ConsoleFilmsIdRoute
  '/console/page-content/$id': typeof ConsolePageContentIdRoute
  '/films/$id/related': typeof FilmsIdRelatedRoute
  '/films/$id/': typeof FilmsIdIndexRoute
  '/console/general/awards/$id': typeof ConsoleGeneralAwardsIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/statistic': typeof StatisticRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/general': typeof ConsoleGeneralRouteRoute
  '/console/page-content': typeof ConsolePageContentRouteRoute
  '/console/pending-films': typeof ConsolePendingFilmsRouteRoute
  '/': typeof HomeIndexRoute
  '/console/general/awards': typeof ConsoleGeneralAwardsRouteRoute
  '/console/general/collections': typeof ConsoleGeneralCollectionsRouteRoute
  '/console/general/countries': typeof ConsoleGeneralCountriesRouteRoute
  '/console/general/genres': typeof ConsoleGeneralGenresRouteRoute
  '/console/general/people': typeof ConsoleGeneralPeopleRouteRoute
  '/console/general/studios': typeof ConsoleGeneralStudiosRouteRoute
  '/console/films/$id': typeof ConsoleFilmsIdRoute
  '/console/page-content/$id': typeof ConsolePageContentIdRoute
  '/films/$id/related': typeof FilmsIdRelatedRoute
  '/films/$id': typeof FilmsIdIndexRoute
  '/console/general/awards/$id': typeof ConsoleGeneralAwardsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/statistic': typeof StatisticRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/general': typeof ConsoleGeneralRouteRoute
  '/console/page-content': typeof ConsolePageContentRouteRoute
  '/console/pending-films': typeof ConsolePendingFilmsRouteRoute
  '/films/$id': typeof FilmsIdRouteRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/console/general_/awards': typeof ConsoleGeneralAwardsRouteRoute
  '/console/general_/collections': typeof ConsoleGeneralCollectionsRouteRoute
  '/console/general_/countries': typeof ConsoleGeneralCountriesRouteRoute
  '/console/general_/genres': typeof ConsoleGeneralGenresRouteRoute
  '/console/general_/people': typeof ConsoleGeneralPeopleRouteRoute
  '/console/general_/studios': typeof ConsoleGeneralStudiosRouteRoute
  '/console/films_/$id': typeof ConsoleFilmsIdRoute
  '/console/page-content_/$id': typeof ConsolePageContentIdRoute
  '/films/$id/related': typeof FilmsIdRelatedRoute
  '/films/$id/': typeof FilmsIdIndexRoute
  '/console/general_/awards_/$id': typeof ConsoleGeneralAwardsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/console'
    | '/login'
    | '/statistic'
    | '/console/collection-events'
    | '/console/films'
    | '/console/general'
    | '/console/page-content'
    | '/console/pending-films'
    | '/films/$id'
    | '/'
    | '/console/general/awards'
    | '/console/general/collections'
    | '/console/general/countries'
    | '/console/general/genres'
    | '/console/general/people'
    | '/console/general/studios'
    | '/console/films/$id'
    | '/console/page-content/$id'
    | '/films/$id/related'
    | '/films/$id/'
    | '/console/general/awards/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/console'
    | '/login'
    | '/statistic'
    | '/console/collection-events'
    | '/console/films'
    | '/console/general'
    | '/console/page-content'
    | '/console/pending-films'
    | '/'
    | '/console/general/awards'
    | '/console/general/collections'
    | '/console/general/countries'
    | '/console/general/genres'
    | '/console/general/people'
    | '/console/general/studios'
    | '/console/films/$id'
    | '/console/page-content/$id'
    | '/films/$id/related'
    | '/films/$id'
    | '/console/general/awards/$id'
  id:
    | '__root__'
    | '/about'
    | '/console'
    | '/login'
    | '/statistic'
    | '/console/collection-events'
    | '/console/films'
    | '/console/general'
    | '/console/page-content'
    | '/console/pending-films'
    | '/films/$id'
    | '/_home/'
    | '/console/general_/awards'
    | '/console/general_/collections'
    | '/console/general_/countries'
    | '/console/general_/genres'
    | '/console/general_/people'
    | '/console/general_/studios'
    | '/console/films_/$id'
    | '/console/page-content_/$id'
    | '/films/$id/related'
    | '/films/$id/'
    | '/console/general_/awards_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRouteRoute: typeof AboutRouteRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  StatisticRouteRoute: typeof StatisticRouteRoute
  FilmsIdRouteRoute: typeof FilmsIdRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistic': {
      id: '/statistic'
      path: '/statistic'
      fullPath: '/statistic'
      preLoaderRoute: typeof StatisticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$id': {
      id: '/films/$id'
      path: '/films/$id'
      fullPath: '/films/$id'
      preLoaderRoute: typeof FilmsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/pending-films': {
      id: '/console/pending-films'
      path: '/pending-films'
      fullPath: '/console/pending-films'
      preLoaderRoute: typeof ConsolePendingFilmsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/page-content': {
      id: '/console/page-content'
      path: '/page-content'
      fullPath: '/console/page-content'
      preLoaderRoute: typeof ConsolePageContentRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general': {
      id: '/console/general'
      path: '/general'
      fullPath: '/console/general'
      preLoaderRoute: typeof ConsoleGeneralRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/films': {
      id: '/console/films'
      path: '/films'
      fullPath: '/console/films'
      preLoaderRoute: typeof ConsoleFilmsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/collection-events': {
      id: '/console/collection-events'
      path: '/collection-events'
      fullPath: '/console/collection-events'
      preLoaderRoute: typeof ConsoleCollectionEventsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/films/$id/': {
      id: '/films/$id/'
      path: '/'
      fullPath: '/films/$id/'
      preLoaderRoute: typeof FilmsIdIndexRouteImport
      parentRoute: typeof FilmsIdRouteRoute
    }
    '/films/$id/related': {
      id: '/films/$id/related'
      path: '/related'
      fullPath: '/films/$id/related'
      preLoaderRoute: typeof FilmsIdRelatedRouteImport
      parentRoute: typeof FilmsIdRouteRoute
    }
    '/console/page-content_/$id': {
      id: '/console/page-content_/$id'
      path: '/page-content/$id'
      fullPath: '/console/page-content/$id'
      preLoaderRoute: typeof ConsolePageContentIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/films_/$id': {
      id: '/console/films_/$id'
      path: '/films/$id'
      fullPath: '/console/films/$id'
      preLoaderRoute: typeof ConsoleFilmsIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general_/studios': {
      id: '/console/general_/studios'
      path: '/general/studios'
      fullPath: '/console/general/studios'
      preLoaderRoute: typeof ConsoleGeneralStudiosRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general_/people': {
      id: '/console/general_/people'
      path: '/general/people'
      fullPath: '/console/general/people'
      preLoaderRoute: typeof ConsoleGeneralPeopleRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general_/genres': {
      id: '/console/general_/genres'
      path: '/general/genres'
      fullPath: '/console/general/genres'
      preLoaderRoute: typeof ConsoleGeneralGenresRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general_/countries': {
      id: '/console/general_/countries'
      path: '/general/countries'
      fullPath: '/console/general/countries'
      preLoaderRoute: typeof ConsoleGeneralCountriesRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general_/collections': {
      id: '/console/general_/collections'
      path: '/general/collections'
      fullPath: '/console/general/collections'
      preLoaderRoute: typeof ConsoleGeneralCollectionsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general_/awards': {
      id: '/console/general_/awards'
      path: '/general/awards'
      fullPath: '/console/general/awards'
      preLoaderRoute: typeof ConsoleGeneralAwardsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/general_/awards_/$id': {
      id: '/console/general_/awards_/$id'
      path: '/general/awards/$id'
      fullPath: '/console/general/awards/$id'
      preLoaderRoute: typeof ConsoleGeneralAwardsIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleCollectionEventsRouteRoute: typeof ConsoleCollectionEventsRouteRoute
  ConsoleFilmsRouteRoute: typeof ConsoleFilmsRouteRoute
  ConsoleGeneralRouteRoute: typeof ConsoleGeneralRouteRoute
  ConsolePageContentRouteRoute: typeof ConsolePageContentRouteRoute
  ConsolePendingFilmsRouteRoute: typeof ConsolePendingFilmsRouteRoute
  ConsoleGeneralAwardsRouteRoute: typeof ConsoleGeneralAwardsRouteRoute
  ConsoleGeneralCollectionsRouteRoute: typeof ConsoleGeneralCollectionsRouteRoute
  ConsoleGeneralCountriesRouteRoute: typeof ConsoleGeneralCountriesRouteRoute
  ConsoleGeneralGenresRouteRoute: typeof ConsoleGeneralGenresRouteRoute
  ConsoleGeneralPeopleRouteRoute: typeof ConsoleGeneralPeopleRouteRoute
  ConsoleGeneralStudiosRouteRoute: typeof ConsoleGeneralStudiosRouteRoute
  ConsoleFilmsIdRoute: typeof ConsoleFilmsIdRoute
  ConsolePageContentIdRoute: typeof ConsolePageContentIdRoute
  ConsoleGeneralAwardsIdRoute: typeof ConsoleGeneralAwardsIdRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleCollectionEventsRouteRoute: ConsoleCollectionEventsRouteRoute,
  ConsoleFilmsRouteRoute: ConsoleFilmsRouteRoute,
  ConsoleGeneralRouteRoute: ConsoleGeneralRouteRoute,
  ConsolePageContentRouteRoute: ConsolePageContentRouteRoute,
  ConsolePendingFilmsRouteRoute: ConsolePendingFilmsRouteRoute,
  ConsoleGeneralAwardsRouteRoute: ConsoleGeneralAwardsRouteRoute,
  ConsoleGeneralCollectionsRouteRoute: ConsoleGeneralCollectionsRouteRoute,
  ConsoleGeneralCountriesRouteRoute: ConsoleGeneralCountriesRouteRoute,
  ConsoleGeneralGenresRouteRoute: ConsoleGeneralGenresRouteRoute,
  ConsoleGeneralPeopleRouteRoute: ConsoleGeneralPeopleRouteRoute,
  ConsoleGeneralStudiosRouteRoute: ConsoleGeneralStudiosRouteRoute,
  ConsoleFilmsIdRoute: ConsoleFilmsIdRoute,
  ConsolePageContentIdRoute: ConsolePageContentIdRoute,
  ConsoleGeneralAwardsIdRoute: ConsoleGeneralAwardsIdRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

interface FilmsIdRouteRouteChildren {
  FilmsIdRelatedRoute: typeof FilmsIdRelatedRoute
  FilmsIdIndexRoute: typeof FilmsIdIndexRoute
}

const FilmsIdRouteRouteChildren: FilmsIdRouteRouteChildren = {
  FilmsIdRelatedRoute: FilmsIdRelatedRoute,
  FilmsIdIndexRoute: FilmsIdIndexRoute,
}

const FilmsIdRouteRouteWithChildren = FilmsIdRouteRoute._addFileChildren(
  FilmsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutRouteRoute: AboutRouteRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  StatisticRouteRoute: StatisticRouteRoute,
  FilmsIdRouteRoute: FilmsIdRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
