/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticRouteRouteImport } from './routes/statistic/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as AboutRouteRouteImport } from './routes/about/route'
import { Route as HomeIndexRouteImport } from './routes/_home/index'
import { Route as FilmsIdRouteRouteImport } from './routes/films/$id/route'
import { Route as ConsoleStudiosRouteRouteImport } from './routes/console/studios/route'
import { Route as ConsolePeopleRouteRouteImport } from './routes/console/people/route'
import { Route as ConsolePendingFilmsRouteRouteImport } from './routes/console/pending-films/route'
import { Route as ConsolePageContentRouteRouteImport } from './routes/console/page-content/route'
import { Route as ConsoleGenresRouteRouteImport } from './routes/console/genres/route'
import { Route as ConsoleFilmsRouteRouteImport } from './routes/console/films/route'
import { Route as ConsoleCountriesRouteRouteImport } from './routes/console/countries/route'
import { Route as ConsoleCollectionsRouteRouteImport } from './routes/console/collections/route'
import { Route as ConsoleCollectionEventsRouteRouteImport } from './routes/console/collection-events/route'
import { Route as ConsoleAwardsRouteRouteImport } from './routes/console/awards/route'
import { Route as FilmsIdIndexRouteImport } from './routes/films/$id/index'
import { Route as FilmsIdRelatedRouteImport } from './routes/films/$id/related'
import { Route as ConsolePageContentIdRouteImport } from './routes/console/page-content_/$id'
import { Route as ConsoleFilmsIdRouteImport } from './routes/console/films_/$id'
import { Route as ConsoleAwardsIdRouteImport } from './routes/console/awards_/$id'

const StatisticRouteRoute = StatisticRouteRouteImport.update({
  id: '/statistic',
  path: '/statistic',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRouteRoute = AboutRouteRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsIdRouteRoute = FilmsIdRouteRouteImport.update({
  id: '/films/$id',
  path: '/films/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleStudiosRouteRoute = ConsoleStudiosRouteRouteImport.update({
  id: '/studios',
  path: '/studios',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsolePeopleRouteRoute = ConsolePeopleRouteRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsolePendingFilmsRouteRoute =
  ConsolePendingFilmsRouteRouteImport.update({
    id: '/pending-films',
    path: '/pending-films',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsolePageContentRouteRoute = ConsolePageContentRouteRouteImport.update({
  id: '/page-content',
  path: '/page-content',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleGenresRouteRoute = ConsoleGenresRouteRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFilmsRouteRoute = ConsoleFilmsRouteRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCountriesRouteRoute = ConsoleCountriesRouteRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCollectionsRouteRoute = ConsoleCollectionsRouteRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleCollectionEventsRouteRoute =
  ConsoleCollectionEventsRouteRouteImport.update({
    id: '/collection-events',
    path: '/collection-events',
    getParentRoute: () => ConsoleRouteRoute,
  } as any)
const ConsoleAwardsRouteRoute = ConsoleAwardsRouteRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const FilmsIdIndexRoute = FilmsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FilmsIdRouteRoute,
} as any)
const FilmsIdRelatedRoute = FilmsIdRelatedRouteImport.update({
  id: '/related',
  path: '/related',
  getParentRoute: () => FilmsIdRouteRoute,
} as any)
const ConsolePageContentIdRoute = ConsolePageContentIdRouteImport.update({
  id: '/page-content_/$id',
  path: '/page-content/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleFilmsIdRoute = ConsoleFilmsIdRouteImport.update({
  id: '/films_/$id',
  path: '/films/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleAwardsIdRoute = ConsoleAwardsIdRouteImport.update({
  id: '/awards_/$id',
  path: '/awards/$id',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/about': typeof AboutRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/statistic': typeof StatisticRouteRoute
  '/console/awards': typeof ConsoleAwardsRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/collections': typeof ConsoleCollectionsRouteRoute
  '/console/countries': typeof ConsoleCountriesRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/genres': typeof ConsoleGenresRouteRoute
  '/console/page-content': typeof ConsolePageContentRouteRoute
  '/console/pending-films': typeof ConsolePendingFilmsRouteRoute
  '/console/people': typeof ConsolePeopleRouteRoute
  '/console/studios': typeof ConsoleStudiosRouteRoute
  '/films/$id': typeof FilmsIdRouteRouteWithChildren
  '/': typeof HomeIndexRoute
  '/console/awards/$id': typeof ConsoleAwardsIdRoute
  '/console/films/$id': typeof ConsoleFilmsIdRoute
  '/console/page-content/$id': typeof ConsolePageContentIdRoute
  '/films/$id/related': typeof FilmsIdRelatedRoute
  '/films/$id/': typeof FilmsIdIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/statistic': typeof StatisticRouteRoute
  '/console/awards': typeof ConsoleAwardsRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/collections': typeof ConsoleCollectionsRouteRoute
  '/console/countries': typeof ConsoleCountriesRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/genres': typeof ConsoleGenresRouteRoute
  '/console/page-content': typeof ConsolePageContentRouteRoute
  '/console/pending-films': typeof ConsolePendingFilmsRouteRoute
  '/console/people': typeof ConsolePeopleRouteRoute
  '/console/studios': typeof ConsoleStudiosRouteRoute
  '/': typeof HomeIndexRoute
  '/console/awards/$id': typeof ConsoleAwardsIdRoute
  '/console/films/$id': typeof ConsoleFilmsIdRoute
  '/console/page-content/$id': typeof ConsolePageContentIdRoute
  '/films/$id/related': typeof FilmsIdRelatedRoute
  '/films/$id': typeof FilmsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/about': typeof AboutRouteRoute
  '/console': typeof ConsoleRouteRouteWithChildren
  '/login': typeof LoginRouteRoute
  '/statistic': typeof StatisticRouteRoute
  '/console/awards': typeof ConsoleAwardsRouteRoute
  '/console/collection-events': typeof ConsoleCollectionEventsRouteRoute
  '/console/collections': typeof ConsoleCollectionsRouteRoute
  '/console/countries': typeof ConsoleCountriesRouteRoute
  '/console/films': typeof ConsoleFilmsRouteRoute
  '/console/genres': typeof ConsoleGenresRouteRoute
  '/console/page-content': typeof ConsolePageContentRouteRoute
  '/console/pending-films': typeof ConsolePendingFilmsRouteRoute
  '/console/people': typeof ConsolePeopleRouteRoute
  '/console/studios': typeof ConsoleStudiosRouteRoute
  '/films/$id': typeof FilmsIdRouteRouteWithChildren
  '/_home/': typeof HomeIndexRoute
  '/console/awards_/$id': typeof ConsoleAwardsIdRoute
  '/console/films_/$id': typeof ConsoleFilmsIdRoute
  '/console/page-content_/$id': typeof ConsolePageContentIdRoute
  '/films/$id/related': typeof FilmsIdRelatedRoute
  '/films/$id/': typeof FilmsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/about'
    | '/console'
    | '/login'
    | '/statistic'
    | '/console/awards'
    | '/console/collection-events'
    | '/console/collections'
    | '/console/countries'
    | '/console/films'
    | '/console/genres'
    | '/console/page-content'
    | '/console/pending-films'
    | '/console/people'
    | '/console/studios'
    | '/films/$id'
    | '/'
    | '/console/awards/$id'
    | '/console/films/$id'
    | '/console/page-content/$id'
    | '/films/$id/related'
    | '/films/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/console'
    | '/login'
    | '/statistic'
    | '/console/awards'
    | '/console/collection-events'
    | '/console/collections'
    | '/console/countries'
    | '/console/films'
    | '/console/genres'
    | '/console/page-content'
    | '/console/pending-films'
    | '/console/people'
    | '/console/studios'
    | '/'
    | '/console/awards/$id'
    | '/console/films/$id'
    | '/console/page-content/$id'
    | '/films/$id/related'
    | '/films/$id'
  id:
    | '__root__'
    | '/about'
    | '/console'
    | '/login'
    | '/statistic'
    | '/console/awards'
    | '/console/collection-events'
    | '/console/collections'
    | '/console/countries'
    | '/console/films'
    | '/console/genres'
    | '/console/page-content'
    | '/console/pending-films'
    | '/console/people'
    | '/console/studios'
    | '/films/$id'
    | '/_home/'
    | '/console/awards_/$id'
    | '/console/films_/$id'
    | '/console/page-content_/$id'
    | '/films/$id/related'
    | '/films/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRouteRoute: typeof AboutRouteRoute
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRoute
  StatisticRouteRoute: typeof StatisticRouteRoute
  FilmsIdRouteRoute: typeof FilmsIdRouteRouteWithChildren
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistic': {
      id: '/statistic'
      path: '/statistic'
      fullPath: '/statistic'
      preLoaderRoute: typeof StatisticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_home/': {
      id: '/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films/$id': {
      id: '/films/$id'
      path: '/films/$id'
      fullPath: '/films/$id'
      preLoaderRoute: typeof FilmsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/studios': {
      id: '/console/studios'
      path: '/studios'
      fullPath: '/console/studios'
      preLoaderRoute: typeof ConsoleStudiosRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/people': {
      id: '/console/people'
      path: '/people'
      fullPath: '/console/people'
      preLoaderRoute: typeof ConsolePeopleRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/pending-films': {
      id: '/console/pending-films'
      path: '/pending-films'
      fullPath: '/console/pending-films'
      preLoaderRoute: typeof ConsolePendingFilmsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/page-content': {
      id: '/console/page-content'
      path: '/page-content'
      fullPath: '/console/page-content'
      preLoaderRoute: typeof ConsolePageContentRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/genres': {
      id: '/console/genres'
      path: '/genres'
      fullPath: '/console/genres'
      preLoaderRoute: typeof ConsoleGenresRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/films': {
      id: '/console/films'
      path: '/films'
      fullPath: '/console/films'
      preLoaderRoute: typeof ConsoleFilmsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/countries': {
      id: '/console/countries'
      path: '/countries'
      fullPath: '/console/countries'
      preLoaderRoute: typeof ConsoleCountriesRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/collections': {
      id: '/console/collections'
      path: '/collections'
      fullPath: '/console/collections'
      preLoaderRoute: typeof ConsoleCollectionsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/collection-events': {
      id: '/console/collection-events'
      path: '/collection-events'
      fullPath: '/console/collection-events'
      preLoaderRoute: typeof ConsoleCollectionEventsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/awards': {
      id: '/console/awards'
      path: '/awards'
      fullPath: '/console/awards'
      preLoaderRoute: typeof ConsoleAwardsRouteRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/films/$id/': {
      id: '/films/$id/'
      path: '/'
      fullPath: '/films/$id/'
      preLoaderRoute: typeof FilmsIdIndexRouteImport
      parentRoute: typeof FilmsIdRouteRoute
    }
    '/films/$id/related': {
      id: '/films/$id/related'
      path: '/related'
      fullPath: '/films/$id/related'
      preLoaderRoute: typeof FilmsIdRelatedRouteImport
      parentRoute: typeof FilmsIdRouteRoute
    }
    '/console/page-content_/$id': {
      id: '/console/page-content_/$id'
      path: '/page-content/$id'
      fullPath: '/console/page-content/$id'
      preLoaderRoute: typeof ConsolePageContentIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/films_/$id': {
      id: '/console/films_/$id'
      path: '/films/$id'
      fullPath: '/console/films/$id'
      preLoaderRoute: typeof ConsoleFilmsIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/awards_/$id': {
      id: '/console/awards_/$id'
      path: '/awards/$id'
      fullPath: '/console/awards/$id'
      preLoaderRoute: typeof ConsoleAwardsIdRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface ConsoleRouteRouteChildren {
  ConsoleAwardsRouteRoute: typeof ConsoleAwardsRouteRoute
  ConsoleCollectionEventsRouteRoute: typeof ConsoleCollectionEventsRouteRoute
  ConsoleCollectionsRouteRoute: typeof ConsoleCollectionsRouteRoute
  ConsoleCountriesRouteRoute: typeof ConsoleCountriesRouteRoute
  ConsoleFilmsRouteRoute: typeof ConsoleFilmsRouteRoute
  ConsoleGenresRouteRoute: typeof ConsoleGenresRouteRoute
  ConsolePageContentRouteRoute: typeof ConsolePageContentRouteRoute
  ConsolePendingFilmsRouteRoute: typeof ConsolePendingFilmsRouteRoute
  ConsolePeopleRouteRoute: typeof ConsolePeopleRouteRoute
  ConsoleStudiosRouteRoute: typeof ConsoleStudiosRouteRoute
  ConsoleAwardsIdRoute: typeof ConsoleAwardsIdRoute
  ConsoleFilmsIdRoute: typeof ConsoleFilmsIdRoute
  ConsolePageContentIdRoute: typeof ConsolePageContentIdRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleAwardsRouteRoute: ConsoleAwardsRouteRoute,
  ConsoleCollectionEventsRouteRoute: ConsoleCollectionEventsRouteRoute,
  ConsoleCollectionsRouteRoute: ConsoleCollectionsRouteRoute,
  ConsoleCountriesRouteRoute: ConsoleCountriesRouteRoute,
  ConsoleFilmsRouteRoute: ConsoleFilmsRouteRoute,
  ConsoleGenresRouteRoute: ConsoleGenresRouteRoute,
  ConsolePageContentRouteRoute: ConsolePageContentRouteRoute,
  ConsolePendingFilmsRouteRoute: ConsolePendingFilmsRouteRoute,
  ConsolePeopleRouteRoute: ConsolePeopleRouteRoute,
  ConsoleStudiosRouteRoute: ConsoleStudiosRouteRoute,
  ConsoleAwardsIdRoute: ConsoleAwardsIdRoute,
  ConsoleFilmsIdRoute: ConsoleFilmsIdRoute,
  ConsolePageContentIdRoute: ConsolePageContentIdRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

interface FilmsIdRouteRouteChildren {
  FilmsIdRelatedRoute: typeof FilmsIdRelatedRoute
  FilmsIdIndexRoute: typeof FilmsIdIndexRoute
}

const FilmsIdRouteRouteChildren: FilmsIdRouteRouteChildren = {
  FilmsIdRelatedRoute: FilmsIdRelatedRoute,
  FilmsIdIndexRoute: FilmsIdIndexRoute,
}

const FilmsIdRouteRouteWithChildren = FilmsIdRouteRoute._addFileChildren(
  FilmsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AboutRouteRoute: AboutRouteRoute,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRoute,
  StatisticRouteRoute: StatisticRouteRoute,
  FilmsIdRouteRoute: FilmsIdRouteRouteWithChildren,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
