const DATASET_FOLDER = './dataset/json';
const PUBLIC_DATASET_FOLDER = './public/dataset';
const PUBLIC_DATASET_JSON = PUBLIC_DATASET_FOLDER + '/dataset.json';

export { DATASET_FOLDER, PUBLIC_DATASET_FOLDER, PUBLIC_DATASET_JSON };
