export const collectionsConfig = {
  "Top 10": "avatar",
  "Avatar Universe": "avatar_2",
  "Marvel Cinematic Universe": "iron_man_1",
  "Space": "interstellar",
  "Future": "time",
  "Fantasy": "pirates_1",
  "Robots": "i_robot",
  "Legends": "terminator_2",
  "Invaders": "war_of_the_worlds",
  "Cars": "fordvsferrari",
  "Dystopia": "maze_runner_1",
  "Mysteries of the Past": "indiana_jones_1",
  "Life Story": "hugo",
  "Superheroes": "batman_2",
  "Agents and Detectives": "mission_impossibe_6",
  "Monsters": "jurassic_world",
  "Anime": "your_name",
  "Disaster": "day_after_tomorrow",
  "Martial Arts": "kungfu_panda",
  "Real Events": "chernobyl",
  "Star Wars Universe": "mandalorian",
  "DC Extended Universe": "man_of_steel",
  "Harry Potter Universe": "harry_potter_3",
  "Middle-Earth": "middle_earth_6"
}
