import { Filters } from '@/common/types';

const filtersConfig: Filters = {
  general: [
    {
      title: 'Type',
      property: 'type',
      type: 'checkmark',
      options: ['Film', 'Animation', 'Series'],
      inputType: 'checkbox',
    },
    {
      title: 'Genres',
      property: 'genres',
      type: 'checkmark',
      inputType: 'checkbox',
      options: [
        'Sci-Fi',
        'Adventures',
        'Action',
        'Fantasy',
        'Drama',
        'Comedy',
        'Crime',
        'Romance',
        'Thriller',
      ],
    },
    {
      title: 'Date Range',
      inputs: {
        start: {
          label: 'Start Date',
          property: 'startDate',
        },
        end: {
          label: 'End Date',
          property: 'endDate',
        },
      },
      type: 'daterange',
    },
    {
      title: 'Country',
      property: 'countries',
      type: 'checkmark',
      inputType: 'checkbox',
      options: ['USA', 'UK', 'Canada', 'France', 'Germany', 'Japan'],
    },
    {
      title: 'Studio',
      property: 'production',
      type: 'checkmark',
      inputType: 'checkbox',
      options: [
        'Walt Disney Pictures',
        'Disney Plus',
        'Pixar Animation',
        'Netflix',
        '20th Century FOX',
        'Lionsgate',
        'Warner Bros. Pictures',
        'HBO Max',
        'DreamWorks Pictures',
        'Lucasfilm',
        'Legendary',
        'Columbia Pictures',
        'Amblin Entertainment',
        'DreamWorks Animation',
        'EuropaCorp',
        'Metro-Goldwyn-Mayer',
        'Summit Entertainment',
      ],
    },
  ],
  collections: [
    {
      title: 'Main theme',
      property: 'collections',
      type: 'checkmark',
      inputType: 'radio',
      options: [
        'Any',
        'Space',
        'Future',
        'Fantasy Worlds',
        'Robots',
        'Legends',
        'Invasion',
        'Cars',
        'Dystopia',
        'Mysteries of the Past',
        'Historical Events',
        'Sport',
        'Animals',
        'Criminals',
        'Superheroes',
        'Agents and Detectives',
        'Monsters',
        'Anime',
        'Disaster',
        'Martial Arts',
        'Based on Real Events',
        'Love',
        'Cinematograph',
        'Skills',
        'Christmas',
      ],
    },
    {
      title: 'Cinematic Universes',
      property: 'collections',
      type: 'checkmark',
      inputType: 'radio',
      options: [
        'Marvel Cinematic Universe',
        'Star Wars Universe',
        'DC Extended Universe',
        'Harry Potter Universe',
        'Middle-Earth Universe',
      ],
    },
    {
      title: 'Tops',
      property: 'collections',
      options: ['Top 10'],
      type: 'checkmark',
      inputType: 'radio',
    },
  ],
};

export { filtersConfig };
