export type ErrorCode =
  | 'UNAUTHENTICATED'
  | 'TOKEN_EXPIRED'
  | 'TOKEN_MISSED'
  | 'INTERNAL_SERVER_ERROR'
  | 'NOT_FOUND'
  | 'INCORRECT_CREDENTIALS'
  | 'INVALID_TOKEN'
  | 'BAD_REQUEST'
  | 'NOT_MULTIPART_DATA'
  | 'MISSING_PARAMS';
