import { Collection } from '@/enums';

const collectionTitles = {
  [Collection.DISASTER]: 'Disaster',
  [Collection.CARS]: 'Cars',
  [Collection.INVASION]: 'Invasion',
  [Collection.SPACE]: 'Space',
  [Collection.ROBOTS]: 'Robots',
  [Collection.CRIMINALS]: 'Criminals',
  [Collection.MCU]: 'Marvel Cinematic Universe',
  [Collection.DEU]: 'DC Extended Universe',
  [Collection.FANTASY_WORLDS]: 'Fantasy Worlds',
  [Collection.TOP_10]: 'Top 10',
  [Collection.FUTURE]: 'Future',
  [Collection.LEGENDS]: 'Legends',
  [Collection.SUPERHEROES]: 'Superheroes',
  [Collection.AGENTS_DETECTIVES]: 'Agents and Detectives',
  [Collection.HISTORICAL_EVENTS]: 'Historical Events',
  [Collection.DYSTOPIA]: 'Dystopia',
  [Collection.MARTIAL_ARTS]: 'Martial Arts',
  [Collection.HPU]: 'Harry Potter Universe',
  [Collection.ROM_COM]: 'RomCom',
  [Collection.CINEMATOGRAPH]: 'Cinematograph',
  [Collection.MYSTERIES]: 'Mysteries of the Past',
  [Collection.MONSTERS]: 'Monsters',
  [Collection.CHRISTMAS]: 'Christmas',
  [Collection.SWU]: 'Star Wars Universe',
  [Collection.ANIMALS]: 'Animals',
  [Collection.MEU]: 'Middle-Earth Universe',
  [Collection.BASED_ON_TRUE]: 'Based on a True Story',
  [Collection.SPORT]: 'Sport',
  [Collection.SKILLS]: 'Skills',
  [Collection.ANIME]: 'Anime',
};

export { collectionTitles };
