import { Studio } from '@/enums';

const studioTitles = {
  [Studio.WALT_DISNEY]: 'Walt Disney Pictures',
  [Studio.DISNEY_PLUS]: 'Disney+',
  [Studio.PIXAR]: 'Pixar Animation',
  [Studio.MARVEL_STUDIOS]: 'Marvel Studios',
  [Studio.MARVEL_ENTERTAINMENT]: 'Marvel Entertainment',
  [Studio.TWENTIETH_CENTURY_FOX]: '20th Century FOX',
  [Studio.TWENTIETH_CENTURY_STUDIO]: '20th Century Studio',
  [Studio.WARNER_BROS]: 'Warner Bros. Pictures',
  [Studio.WARNER_BROS_TV]: 'Warner Bros. Television',
  [Studio.SONY]: 'Sony Pictures',
  [Studio.SONY_ANIMATION]: 'Sony Pictures Animation',
  [Studio.COLUMBIA]: 'Columbia Pictures',
  [Studio.UNIVERSAL]: 'Universal Pictures',
  [Studio.PARAMOUNT]: 'Paramount Pictures',
  [Studio.DREAMWORKS]: 'DreamWorks Pictures',
  [Studio.DREAMWORKS_ANIMATION]: 'DreamWorks Animation',
  [Studio.NETFLIX]: 'Netflix',
  [Studio.DC_ENTERTAINMENT]: 'DC Entertainment',
  [Studio.CROSS_CREEK]: 'Cross Creek Pictures',
  [Studio.IMAGINE]: 'Imagine Entertainment',
  [Studio.RIOT_GAMES]: 'Riot Games',
  [Studio.NICKELODEON]: 'Nickelodeon Animation Studios',
  [Studio.LIGHTSTORM]: 'Lightstorm Entertainment',
  [Studio.TSG]: 'TSG Entertainment',
  [Studio.LEGENDARY]: 'Legendary',
  [Studio.HBO]: 'HBO',
  [Studio.EUROPACORP]: 'Europacorp',
  [Studio.THUNDER_ROAD]: 'Thunder Road',
  [Studio.ANTON]: 'Anton',
  [Studio.G_BASE]: 'G-base',
  [Studio.VILLAGE_ROADSHOW]: 'Village Roadshow Pictures',
  [Studio.TAILWIND]: 'Tailwind Productions',
  [Studio.NBC_UNIVERSAL_TV]: 'NBC Universal Television',
  [Studio.UNIVERSAL_MEDIA]: 'Universal Media Studios',
  [Studio.METROPOLITAN_FILMEXPORT]: 'Metropolitan Filmexport',
  [Studio.BLUE_SKY]: 'Blue Sky Studios',
  [Studio.LUCASFILM]: 'Lucasfilm',
  [Studio.TRISTAR]: 'Tristar',
  [Studio.AMBLIN]: 'Amblin Entertainment',
  [Studio.HBO_MAX]: 'HBO Max',
  [Studio.THE_SPA_STUDIOS]: 'The SPA Studios',
  [Studio.ATRESMEDIA_CINE]: 'Atresmedia Cine',
  [Studio.SUMMIT]: 'Summit Entertainment',
  [Studio.JERRY_BRUCKHEIMER_FILMS]: 'Jerry Bruckheimer Films',
  [Studio.BBC_ONE]: 'BBC One',
  [Studio.BAD_ROBOT]: 'Bad Robot Productions',
  [Studio.SYNCOPY]: 'Syncopy',
  [Studio.TF1]: 'TF1 Films Productions',
  [Studio.ARP_SELECTIO]: 'ARP Selectio',
  [Studio.CAROLCO]: 'Carolco Pictures',
  [Studio.HALCYON]: 'The Halcyon Company',
  [Studio.CW]: 'The CW',
  [Studio.CBS]: 'CBS Television Studios',
  [Studio.STX]: 'STX Films',
  [Studio.MIRAMAX]: 'MIRAMAX',
  [Studio.NEW_LINE_CINEMA]: 'New Line Cinema',
  [Studio.LIONSGATE]: 'Lionsgate',
  [Studio.GAUMONT]: 'Gaumont',
  [Studio.TNT]: 'TNT',
  [Studio.ORION]: 'Orion Pictures',
  [Studio.CINEMA_84]: 'Cinema_84',
  [Studio.SKYDANCE]: 'Skydance Productions',
  [Studio.TOHO]: 'Toho Animation',
  [Studio.COMIX_WAVE]: 'Comix Wave Films',
};

export { studioTitles };
