import { type MenuConfigItem } from '../types';
import {
  BuildingIcon,
  CalendarIcon,
  CalendarSyncIcon,
  ClapperboardIcon,
  LibraryIcon,
  MapIcon,
  NewspaperIcon,
  TrophyIcon,
  UserIcon,
  VideotapeIcon,
} from 'lucide-react';

export const consoleMenuConfig: MenuConfigItem[] = [
  {
    id: 'people',
    route: '/console/people',
    title: 'Actors / Creators',
    icon: <UserIcon />,
    color: 'color-blue-dark',
  },
  {
    id: 'awards',
    route: '/console/awards',
    title: 'Awards',
    icon: <TrophyIcon />,
    color: 'color-yellow-primary',
  },
  {
    id: 'collections',
    route: '/console/collections',
    title: 'Collections',
    icon: <LibraryIcon />,
    color: 'color-red-light',
  },
  {
    id: 'collection-events',
    route: '/console/collection-events',
    title: 'Collection Events',
    icon: <CalendarIcon />,
    color: 'color-orange-light',
  },
  {
    id: 'countries',
    route: '/console/countries',
    title: 'Countries',
    icon: <MapIcon />,
    color: 'color-green-primary',
  },
  {
    id: 'films',
    route: '/console/films',
    title: 'Films',
    icon: <ClapperboardIcon />,
    color: 'color-blue-primary',
  },
  {
    id: 'genres',
    route: '/console/genres',
    title: 'Genres',
    icon: <VideotapeIcon />,
    color: 'color-purple-primary',
  },
  {
    id: 'page-content',
    route: '/console/page-content',
    title: 'Pages Content',
    icon: <NewspaperIcon />,
    color: 'color-green-dark',
  },
  {
    id: 'pending-films',
    route: '/console/pending-films',
    title: 'Pending Films',
    icon: <CalendarSyncIcon />,
    color: 'color-orange-primary',
  },
  {
    id: 'studios',
    route: '/console/studios',
    title: 'Studios',
    icon: <BuildingIcon />,
    color: 'color-gray-dark',
  },
];
