// Auto-generated files, don't modify
export const colors = {
  "colorBluePrimary": "var(--color-blue-primary)",
  "colorBlueLight": "var(--color-blue-light)",
  "colorBlueExtraLight": "var(--color-blue-extra-light)",
  "colorBlueInvisible": "var(--color-blue-invisible)",
  "colorBlueDark": "var(--color-blue-dark)",
  "colorGreenPrimary": "var(--color-green-primary)",
  "colorGreenDark": "var(--color-green-dark)",
  "colorGreenInvisible": "var(--color-green-invisible)",
  "colorBlueGreenPrimary": "var(--color-blue-green-primary)",
  "colorLimePrimary": "var(--color-lime-primary)",
  "colorYellowPrimary": "var(--color-yellow-primary)",
  "colorYellowLight": "var(--color-yellow-light)",
  "colorYellowExtraLight": "var(--color-yellow-extra-light)",
  "colorOrangePrimary": "var(--color-orange-primary)",
  "colorOrangeLight": "var(--color-orange-light)",
  "colorBlack": "var(--color-black)",
  "colorWhite": "var(--color-white)",
  "colorGrayPrimary": "var(--color-gray-primary)",
  "colorGrayLight": "var(--color-gray-light)",
  "colorGrayExtraLight": "var(--color-gray-extra-light)",
  "colorGrayInvisible": "var(--color-gray-invisible)",
  "colorGrayLightDark": "var(--color-gray-light-dark)",
  "colorGrayDark": "var(--color-gray-dark)",
  "colorGrayExtraDark": "var(--color-gray-extra-dark)",
  "colorRedPrimary": "var(--color-red-primary)",
  "colorRedLight": "var(--color-red-light)",
  "colorRedExtraLight": "var(--color-red-extra-light)",
  "colorBrownLight": "var(--color-brown-light)",
  "colorPurplePrimary": "var(--color-purple-primary)",
  "colorPurpleLight": "var(--color-purple-light)",
  "colorPurpleDark": "var(--color-purple-dark)"
} as const;

export type Colors = keyof typeof colors;
