export enum ErrorCode {
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  JWT_EXPIRED = 'JWT_EXPIRED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS',
  INVALID_TOKEN = 'INVALID_TOKEN',
}
