import type z from 'zod';
import sanitize from 'sanitize-html';
import { createFileRoute } from '@tanstack/react-router';
import {
  Form,
  Panel,
  isNewItem,
  getArticleByIdQueryOptions,
  type ApiResponse,
  api,
  getEmptyFormValues,
  type Input,
  getMixedId,
  mutateEntity,
  queryKey,
} from '~/shared';
import { SANITIZE_CONFIG } from '@films-collection/shared';
import { ArticleFormSchema } from '~/routes/console/articles_/-schemas';
import { useMutation, useSuspenseQuery } from '@tanstack/react-query';
import { generateSlug } from '~/routes/console/articles_/-helpers';

const getDefaultFormValues = (data: ApiResponse<typeof api.articles.getById> | null) => {
  if (data) {
    return {
      id: data.id,
      title: data.title,
      content: data.content,
      slug: data.slug,
    };
  }

  return getEmptyFormValues<Input<typeof api.articles.create>>({
    title: '',
    slug: '',
    content: '',
  });
};

export const Route = createFileRoute('/console/articles_/$id')({
  loader: async ({ context: { queryClient }, params }) => {
    if (!isNewItem(params.id)) {
      return await queryClient.ensureQueryData(getArticleByIdQueryOptions(+params.id));
    }
  },
  component: RouteComponent,
  staticData: {
    title: 'Articles',
    backPath: '/console/articles',
  },
  head: ({ loaderData }) => ({
    meta: [
      {
        title: `${loaderData?.title ?? 'New article'} - Films Collection`,
      },
    ],
  }),
});

function RouteComponent() {
  const params = Route.useParams();
  const navigate = Route.useNavigate();

  const mixedId = getMixedId(params.id);

  const { data } = useSuspenseQuery(getArticleByIdQueryOptions(mixedId));

  const { mutateAsync, isPending } = useMutation({
    mutationFn: mutateEntity(api.articles.create, api.articles.update),
    onSuccess: () => {
      navigate({
        to: '/console/articles',
      });
    },
    meta: {
      invalidateQueries:
        !isNewItem(mixedId) && data?.slug
          ? [
              {
                queryKey: [queryKey('articles.getBySlug'), data.slug],
              },
              { queryKey: queryKey('articles.getAdminList') },
            ]
          : { queryKey: queryKey('articles.getAdminList') },
    },
  });

  const handleSubmit = async (values: z.infer<typeof ArticleFormSchema>) => {
    const sanitizedContent = sanitize(values.content, SANITIZE_CONFIG);

    await mutateAsync({
      ...values,
      slug: generateSlug(values.title, values.slug),
      content: sanitizedContent,
    });
  };

  return (
    <Form
      onSubmit={handleSubmit}
      defaultValues={getDefaultFormValues(data)}
      schema={ArticleFormSchema}
      isLoading={isPending}
      islandActions
    >
      <Panel isFlexContainer>
        <Form.TextInput name="title" label="Title" />
        <Form.TextEditor name="content" label="Content" />
        <Form.TextInput name="slug" label="Slug" placeholder="Autogenerated from title" />
      </Panel>
    </Form>
  );
}
