name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Authenticate Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth login --access-token $FLY_API_TOKEN

      - name: Set secrets
        env:
          PORT: ${{ secrets.PORT }}
          HOST: ${{ secrets.HOST }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          FRONTEND_ORIGIN: ${{ secrets.FRONTEND_ORIGIN }}
        run: |
          flyctl secrets set PORT=$PORT HOST="$HOST" MONGODB_URI="$MONGODB_URI" FRONTEND_ORIGIN="$FRONTEND_ORIGIN" --app films-collection-server

      - name: Deploy to Fly.io
        run: flyctl deploy --config server/fly.toml --remote-only
