name: Deploy Server

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly
        working-directory: ./server
        run: flyctl deploy --config server/fly.toml --remote-only --app films-collection-server
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}