enum NominationCategory {
  CAST = 'cast',
  DIRECTOR = 'director',
  SCREENPLAY = 'screenplay',
  MUSIC = 'music',
  VISUAL_EFFECTS = 'visual_effects',
  SPECIAL_EFFECTS = 'special_effects',
  SOUND_EFFECTS = 'sound_effects',
  PRODUCTION_DESIGN = 'production_design',
  STUNT_COORDINATOR = 'stunt_coordinator',
  ANIMATION = 'animation',
  CINEMATOGRAPHY = 'cinematography',
  EDITING = 'editing',
  MAKE_UP = 'make_up',
  GENRE = 'genre',
  DVD = 'dvd',
  ADAPTATION = 'adaption',
  ART = 'art_direction',
  COSTUMES = 'costumes',
  BEST_MOVIE = 'best_movie',
  BEST_OF_YEAR = 'best_of_year',
  ACTION = 'action',
  CASTING = 'casting',
}

export { NominationCategory };
